import '../../node_modules/normalize.css';
import './style.less';
import '../img/title.png';
import '../img/follow.png';
import '../img/tencent.png';
import '../img/alibaba.png';
import '../img/baidu.png';
import '../img/wangyi.png';
import '../../node_modules/lib-flexible/flexible.js';